#!/usr/bin/python

#The base of this code comes from:
#https://hackernoon.com/prime-numbers-using-python-824ff4b3ea19

#This code just checks if a number is prime
#(This is for you, Jalen)

possiblePrime = 1000001

# Assume number is prime until shown it is not.
isPrime = True
for num in range(2, possiblePrime):
    if possiblePrime % num == 0:
        isPrime = False

if isPrime:
    print possiblePrime, 'is prime'
else:
    print possiblePrime, 'is not prime'
