#!/usr/bin/python

#this generates the sequence p_n

#basically EXPERIMENTAL but for the p_n

p=2
max= 30
pList = []

print 'p_ 0 =',p        #we need this so the numbering works down the road
print 'this is a prime'

for i in range (1,max+1):
    p=p + 3*2**(i-1)

    print 'p_',i,'=',p
    pList.append (p)

for possiblePrime in pList: #this is where we check for primes

    # Assume number is prime until shown it is not.
    isPrime = True
    for num in range(2, possiblePrime):
        if possiblePrime % num == 0:
            isPrime = False

    if isPrime:
        print possiblePrime, 'is a prime'
print 'done'
