#!/usr/bin/python

# we use this program to compare the orignial sequence, a_n,
# with some other sequence to see if we can find a constraint on it.

#here is the original sequence
a0 = 5
a1 = 12
a2 = 13

ex0 = 2    #this is an example value that we can use to check against it
ex = 3

max= 25     #highest n value solved for

for i in range (3,max+1):
    a3 = a2+a1-a0
    a0=a1
    a1=a2
    a2=a3

    ex=ex0 + ex*i
    ex0=ex

    print 'a_',i,'=',a3, '  constraint=', ex
